services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vrscorekeeper
      POSTGRES_USER: vruser
      POSTGRES_PASSWORD: vrpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: vrscorekeeper
      POSTGRES_USER: vruser
      POSTGRES_PASSWORD: vrpassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: "your-dev-secret-key"
      DJANGO_SETTINGS_MODULE: settings.settings.prod

volumes:
  postgres_data:
