# Generated by Django 5.1.5 on 2025-01-21 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_tournaments', '0004_alter_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
