# Generated by Django 5.1.5 on 2025-02-20 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_tournaments', '0006_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
