# Generated by Django 5.1.5 on 2025-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_tournaments', '0007_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
