# Generated by Django 5.1.5 on 2026-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_tournaments', '0008_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='points_to_win',
            field=models.IntegerField(default=40),
        ),
    ]
