# Generated by Django 5.1.5 on 2026-05-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_tournaments', '0009_tournament_points_to_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='points_to_win',
            field=models.IntegerField(default=0),
        ),
    ]
